# Generated by Django 2.2.7 on 2019-11-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='finish_date',
        ),
    ]
