# Generated by Django 2.2.7 on 2019-11-25 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_remove_todolist_finish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='last_name',
        ),
    ]
